server:
  port: 8083
spring:
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml
    enabled: true
  kafka:
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: txn-banking
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  datasource:
    url: jdbc:postgresql://localhost:4321/notification
    password: notes
    username: postgres
    sql:
      init:
        mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: none
    hibernate:
      ddl-auto: none
    show-sql: false
    defer-datasource-initialization: false

  main:
    allow-bean-definition-overriding: true
  application:
    name: notification-service
